name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: show initial iptables
        run: |
          sudo iptables -vnL
      - uses: xStar20/clear@v1
      - name: check post action iptables
        run: sudo iptables -vnL
      - name: check
        run: test/iptables-save-count.sh
